=== dsg-unipr/deus/schema/automator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
	targetNamespace="http://dsg.ce.unipr.it/software/deus/schema/automator"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://dsg.ce.unipr.it/software/deus/schema/automator">

	<complexType name="event">
		<sequence>
			<element name="logger" type="tns:logger" minOccurs="0"
				maxOccurs="1" />
			<element name="params" type="tns:params" minOccurs="0"
				maxOccurs="1">
			</element>
			<element name="events" type="tns:references" minOccurs="0"
				maxOccurs="1">
			</element>
		</sequence>
		<attribute name="id" type="string" use="required"></attribute>
		<attribute name="handler" type="string" use="required"></attribute>
		<attribute name="schedulerListener" type="string" use="optional"></attribute>
		<attribute name="oneShot" type="boolean" use="optional"></attribute>
		<attribute name="distributionLevel" type="string" use="optional"></attribute>
	</complexType>

	<complexType name="node">
		<sequence>
			<element name="logger" type="tns:logger" minOccurs="0"
				maxOccurs="1" />
			<element name="params" type="tns:params" minOccurs="0"
				maxOccurs="1">
			</element>
			<element name="resources" type="tns:resources" minOccurs="0"
				maxOccurs="1">
			</element>
		</sequence>
		<attribute name="id" type="string" use="required"></attribute>
		<attribute name="handler" type="string" use="required"></attribute>
	</complexType>

	<complexType name="resources">
		<sequence>
			<element name="resource" type="tns:resource" maxOccurs="unbounded"
				minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="resource">
		<sequence>
			<element name="params" type="tns:params" minOccurs="0"
				maxOccurs="1">
			</element>
		</sequence>
		<attribute name="handler" type="string" use="required"></attribute>
	</complexType>

	<complexType name="process">
		<sequence>
			<element name="logger" type="tns:logger" minOccurs="0"
				maxOccurs="1" />
			<element name="params" type="tns:params" minOccurs="0"
				maxOccurs="1">
			</element>
			<element name="nodes" type="tns:references" minOccurs="0"
				maxOccurs="1">
			</element>
			<element name="events" type="tns:references" minOccurs="1"
				maxOccurs="1">
			</element>
		</sequence>
		<attribute name="id" type="string" use="required"></attribute>
		<attribute name="handler" type="string" use="required"></attribute>
	</complexType>
	
	<complexType name="network">
		<sequence>
			<element name="nodes" type="tns:references" minOccurs="1"
				maxOccurs="1">
			</element>
		</sequence>
		<attribute name="id" type="string" use="required"></attribute>
		<attribute name="handler" type="string" use="required"></attribute>
	</complexType>

	<complexType name="engine">
		<sequence>
			<element name="logger" type="tns:logger" minOccurs="0"
				maxOccurs="1" />
			<element name="processes" type="tns:references"
				minOccurs="1" maxOccurs="1">
			</element>
		</sequence>
		<attribute name="maxvt" type="float" use="required"></attribute>
		<attribute name="seed" type="int" use="required"></attribute>
		<attribute name="keyspacesize" type="int" use="optional"></attribute>
		<attribute name="prng" type="string" use="optional"/>
	</complexType>

	<complexType name="params">
		<sequence>
			<element name="param" type="tns:param" maxOccurs="unbounded"
				minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="param">
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="value" type="string" use="required"></attribute>
	</complexType>

	<complexType name="references">
		<sequence>
			<element name="reference" type="tns:reference"
				maxOccurs="unbounded" minOccurs="1">
				<keyref name="entityKeyRef" refer="tns:entityKey">
					<selector xpath=".//tns:*/*" />
					<field xpath="@id" />
				</keyref>
				<key name="entityKey">
					<selector xpath=".//tns:*" />
					<field xpath="@id" />
				</key>
			</element>
		</sequence>
	</complexType>

	<complexType name="reference">
		<attribute name="id" type="string" use="required"></attribute>
		<attribute name="number" type="int"></attribute>
	</complexType>

	<complexType name="logger">
		<attribute name="level" use="required">
			<simpleType>
				<restriction base="string">
					<enumeration value="OFF" />
					<enumeration value="SEVERE" />
					<enumeration value="WARNING" />
					<enumeration value="INFO" />
					<enumeration value="CONFIG" />
					<enumeration value="FINE" />
					<enumeration value="FINER" />
					<enumeration value="FINEST" />
					<enumeration value="ALL" />
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="pathPrefix" type="string" use="optional" />
	</complexType>

	<complexType name="automator">
		<sequence>
			<element name="event" type="tns:event" minOccurs="0"
				maxOccurs="unbounded">
			</element>
			<element name="node" type="tns:node" minOccurs="0"
				maxOccurs="unbounded">
			</element>
			<element name="process" type="tns:process" minOccurs="0"
				maxOccurs="unbounded">
			</element>
			<element name="network" type="tns:network" minOccurs="0"
				maxOccurs="1">
			</element>
			<element name="engine" type="tns:engine" minOccurs="1"
				maxOccurs="1">
			</element>
		</sequence>
	</complexType>

	<!--  da fare, rendere gli ID univoci in tutto il file -->
	<element name="automator" type="tns:automator">
		<keyref name="eventKeyRef" refer="tns:eventKey">
			<selector xpath=".//tns:events/*" />
			<field xpath="@id" />
		</keyref>
		<key name="eventKey">
			<selector xpath=".//tns:event" />
			<field xpath="@id" />
		</key>
		<keyref name="nodeKeyRef" refer="tns:nodeKey">
			<selector xpath=".//tns:nodes/*" />
			<field xpath="@id" />
		</keyref>
		<key name="nodeKey">
			<selector xpath=".//tns:node" />
			<field xpath="@id" />
		</key>
		<keyref name="processKeyRef" refer="tns:processKey">
			<selector xpath=".//tns:processes/*" />
			<field xpath="@id" />
		</keyref>
		<key name="processKey">
			<selector xpath=".//tns:process" />
			<field xpath="@id" />
		</key>
	</element>
</schema>

=== dsg-unipr/deus/examples/recursivenetworks/RecursiveNetworkBA.xml
<?xml version="1.0" encoding="UTF-8"?>
<aut:automator
	xmlns:aut="http://dsg.ce.unipr.it/software/deus/schema/automator"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://dsg.ce.unipr.it/software/deus/schema/automator ../../schema/automator.xsd ">


	<!-- *** EVENTS *** -->

	<aut:event id="birth" handler="it.unipr.ce.dsg.deus.impl.event.BirthEvent" 
		schedulerListener="it.unipr.ce.dsg.deus.example.recursivenetworks.RecursiveNetworkBirthSchedulerListener" />

	<aut:event id="connection" handler="it.unipr.ce.dsg.deus.example.recursivenetworks.BATopologyBuilderEvent" oneShot="true" >
		<aut:params>
			<aut:param name="isBidirectional" value="true" />
			<aut:param name="n0" value="6" />
			<aut:param name="m" value="5" />
		</aut:params>
	</aut:event>
	
	<aut:event id="configuration" handler="it.unipr.ce.dsg.deus.example.recursivenetworks.RecursiveNetworkConfigurationEvent" oneShot="true" >
		<aut:params>
			<aut:param name="thirdLevel" value="false" />
			<aut:param name="nohr" value="true" />
			<aut:param name="maxRTSize" value="10" />
		</aut:params>
	</aut:event>
	
	<aut:event id="rtupdate" handler="it.unipr.ce.dsg.deus.example.recursivenetworks.RecursiveNetworkRTUpdateEvent" >
		<aut:params>
			<aut:param name="thirdLevel" value="false" />
			<aut:param name="nohr" value="true" />
			<aut:param name="deltaRTSize" value="10" />
		</aut:params>
	</aut:event>
	
 	<aut:event id="exploration" handler="it.unipr.ce.dsg.deus.example.recursivenetworks.RecursiveNetworkExplorationEvent" oneShot="true" >
 		<aut:params>
			<aut:param name="strategy" value="flooding" /> <!-- "hr", "flooding" or "random" -->
		</aut:params>
	</aut:event>
	
	<aut:event id="logRecursiveNetworkStats" handler="it.unipr.ce.dsg.deus.example.recursivenetworks.LogRecursiveNetworkStatsEvent" />
	
	<aut:event id="routing" handler="it.unipr.ce.dsg.deus.example.recursivenetworks.RecursiveNetworkRoutingEvent" oneShot="true" >
 		<aut:params>
			<aut:param name="max" value="100" />
			<aut:param name="advanced" value="false" />
			<aut:param name="nohr" value="true" />
		</aut:params>
	</aut:event>
	
	<!-- *** NODE SPECIES *** -->

	<aut:node id="recursiveNetworkNode" handler="it.unipr.ce.dsg.deus.example.recursivenetworks.RecursiveNetworkPeer" >
		<aut:params>
			<aut:param name="numSubnetworks" value="20" />
		</aut:params>
	</aut:node>


	<!-- *** PROCESSES *** -->

	<!-- with 1/lambda = 1000 and 1/lambda' = 1000000, we have E[N] = lambda/lambda' = 1000 -->

	<aut:process id="rectpulseperiodic1" handler="it.unipr.ce.dsg.deus.impl.process.RectangularPulsePeriodicProcess">
		<aut:params>
			<aut:param name="period" value="1" />
			<aut:param name="startVtThreshold" value="0" />
			<aut:param name="stopVtThreshold" value="1000" />
		</aut:params>
		<aut:nodes>
			<aut:reference id="recursiveNetworkNode" />
		</aut:nodes>
		<aut:events>
			<aut:reference id="birth" />
		</aut:events>
	</aut:process>

	<aut:process id="periodic0" handler="it.unipr.ce.dsg.deus.impl.process.PeriodicProcess">
		<aut:params>
			<aut:param name="period" value="1001" />
		</aut:params>
		<aut:nodes>
			<aut:reference id="recursiveNetworkNode" />
		</aut:nodes>
		<aut:events>
			<aut:reference id="connection" />
		</aut:events>
	</aut:process>
	
	<aut:process id="periodic1" handler="it.unipr.ce.dsg.deus.impl.process.PeriodicProcess">
		<aut:params>
			<aut:param name="period" value="2000" />
		</aut:params>
		<aut:nodes>
			<aut:reference id="recursiveNetworkNode" />
		</aut:nodes>
		<aut:events>
			<aut:reference id="configuration" />
		</aut:events>
	</aut:process>

	<aut:process id="periodic2" handler="it.unipr.ce.dsg.deus.impl.process.PeriodicProcess">
		<aut:params>
			<aut:param name="period" value="3000" />
		</aut:params>
		<aut:nodes>
			<aut:reference id="recursiveNetworkNode" />
		</aut:nodes>
		<aut:events>
			<aut:reference id="exploration" />
		</aut:events>
	</aut:process>
	
	<aut:process id="periodic3" handler="it.unipr.ce.dsg.deus.impl.process.RectangularPulsePeriodicProcess">
		<aut:params>
			<aut:param name="period" value="1000" />
			<aut:param name="startVtThreshold" value="0" />
			<aut:param name="stopVtThreshold" value="15000" />
		</aut:params>
		<aut:events>
			<aut:reference id="logRecursiveNetworkStats" />  
		</aut:events>
	</aut:process>
	
	<aut:process id="periodic4" handler="it.unipr.ce.dsg.deus.impl.process.PeriodicProcess">
		<aut:params>
			<aut:param name="period" value="2100" />
		</aut:params>
		<aut:nodes>
			<aut:reference id="recursiveNetworkNode" />
		</aut:nodes>
		<aut:events>
			<aut:reference id="routing" />
		</aut:events>
	</aut:process>
	
	<aut:process id="periodic5" handler="it.unipr.ce.dsg.deus.impl.process.RectangularPulsePeriodicProcess">
		<aut:params>
			<aut:param name="period" value="1000" />
			<aut:param name="startVtThreshold" value="2000" />
			<aut:param name="stopVtThreshold" value="15000" />
		</aut:params>
		<aut:nodes>
			<aut:reference id="recursiveNetworkNode" />
		</aut:nodes>
		<aut:events>
			<aut:reference id="rtupdate" />
		</aut:events>
	</aut:process>


	<!-- *** SIMULATION *** -->

	<aut:engine maxvt="15010" seed="123456789"> 
		<aut:logger level="INFO" />
		<aut:processes>
			<aut:reference id="rectpulseperiodic1" />
			<aut:reference id="periodic0" />
			<aut:reference id="periodic1" /> 
			<!-- aut:reference id="periodic2" / --> 
			<aut:reference id="periodic3" />
			<aut:reference id="periodic4" />
			<aut:reference id="periodic5" />
		</aut:processes>
	</aut:engine>

</aut:automator>

=== dsg-unipr/deus/examples/basic/SingleSpeedGrowthExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<aut:automator
	xmlns:aut="http://dsg.ce.unipr.it/software/deus/schema/automator"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://dsg.ce.unipr.it/software/deus/schema/automator automator.xsd ">


	<!-- *** EVENTS *** -->

	<aut:event id="nodeDeath" handler="it.unipr.ce.dsg.deus.impl.event.DeathEvent" oneShot="true" />
	<!-- when scheduled, deletes a node -->

	<aut:event id="nodeBirth" handler="it.unipr.ce.dsg.deus.impl.event.BirthEvent" schedulerListener="it.unipr.ce.dsg.deus.example.basic.BirthSchedulerListener"><!-- when scheduled, creates a new node -->
		<aut:events>
			<aut:reference id="nodeDeath" /><!-- event to be scheduled on created node -->
		</aut:events>
	</aut:event>

	<aut:event id="logPopulationSize" handler="it.unipr.ce.dsg.deus.impl.event.LogPopulationSizeEvent" />

	<!-- *** NODE SPECIES *** -->

	<aut:node id="basicnode" handler="it.unipr.ce.dsg.deus.impl.node.BasicNode">
	</aut:node>

	<!-- *** PROCESSES *** -->

	<!-- with 1/lambda = 50 and 1/lambda' = 20000, we have E[N] = 400 -->

	<aut:process id="poissonA" handler="it.unipr.ce.dsg.deus.impl.process.PoissonProcess">
		<aut:params>
			<aut:param name="meanArrival" value="50" />
		</aut:params>
		<aut:nodes>
			<aut:reference id="basicnode" /><!-- this is to associate the process to a specific type of nodes -->
		</aut:nodes>
		<aut:events>
			<aut:reference id="nodeBirth" />
		</aut:events>
	</aut:process>

	<aut:process id="poissonB" handler="it.unipr.ce.dsg.deus.impl.process.PoissonProcess">
		<aut:params>
			<aut:param name="meanArrival" value="20000" />
		</aut:params>
		<aut:nodes>
			<aut:reference id="basicnode" />
		</aut:nodes>
		<aut:events>
			<aut:reference id="nodeDeath" />
		</aut:events>
	</aut:process>

	<aut:process id="periodic1" handler="it.unipr.ce.dsg.deus.impl.process.PeriodicProcess">
		<aut:params>
			<aut:param name="period" value="500" />
		</aut:params>
		<aut:events>
			<aut:reference id="logPopulationSize" />
		</aut:events>
	</aut:process>

	<!-- *** SIMULATION *** -->

	<aut:engine maxvt="200000"
		seed="123456789">
		<aut:logger level="ALL" pathPrefix="log" />
		<aut:processes>
			<aut:reference id="poissonA" />
			<aut:reference id="periodic1" />			
		</aut:processes>
	</aut:engine>

</aut:automator>

=== dsg-unipr/deus/examples/basic/RandomWalkExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<aut:automator
	xmlns:aut="http://dsg.ce.unipr.it/software/deus/schema/automator"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://dsg.ce.unipr.it/software/deus/schema/automator automator.xsd ">


	<!-- *** EVENTS *** -->

	<aut:event id="birth" handler="it.unipr.ce.dsg.deus.impl.event.BirthEvent"
	 schedulerListener="it.unipr.ce.dsg.deus.example.basic.BirthSchedulerListener"><!-- when scheduled, creates a new node -->
		<aut:params>
			<aut:param name="hasSameAssociatedNode" value="false" />
		</aut:params>
		<aut:events><!-- events to be scheduled on created node -->
		    <aut:reference id="connection" />
		</aut:events>
	</aut:event>

	<aut:event id="connection" handler="it.unipr.ce.dsg.deus.p2p.event.SingleConnectionEvent" schedulerListener="it.unipr.ce.dsg.deus.example.basic.SingleConnectionSchedulerListener" oneShot="true" >
		<aut:params>
			<aut:param name="isBidirectional" value="true" />
			<aut:param name="hasSameAssociatedNode" value="false" />
		</aut:params>
	</aut:event>	
	
	<aut:event id="randomwalk" handler="it.unipr.ce.dsg.deus.example.basic.RandomWalkEvent" oneShot="false" >
		<aut:params>
			<aut:param name="hasSameAssociatedNode" value="false" />
		</aut:params>
	</aut:event>

	<aut:event id="logPopulationSize" handler="it.unipr.ce.dsg.deus.impl.event.LogPopulationSizeEvent" />

	<aut:event id="logNodeDegree" handler="it.unipr.ce.dsg.deus.p2p.event.LogNodeDegreeEvent">
		<aut:params>
			<aut:param name="kMax" value="50" />
		</aut:params>
	</aut:event>


	<!-- *** NODE SPECIES *** -->

	<aut:node id="supernode" handler="it.unipr.ce.dsg.deus.p2p.node.Peer" />

	<!-- *** PROCESSES *** -->

	<!-- with 1/lambda = 50 and 1/lambda' = 20000, we have E[N] = 400 -->

	<aut:process id="periodic1" handler="it.unipr.ce.dsg.deus.impl.process.RectangularPulsePeriodicProcess">
		<aut:params>
			<aut:param name="period" value="1" />
			<aut:param name="startVtThreshold" value="0" />
			<aut:param name="stopVtThreshold" value="1000" />
		</aut:params>
		<aut:nodes>
			<aut:reference id="supernode" />
		</aut:nodes>
		<aut:events>
			<aut:reference id="birth" />
		</aut:events>
	</aut:process>
	
	<aut:process id="periodic2" handler="it.unipr.ce.dsg.deus.impl.process.PeriodicProcess">
		<aut:params>
			<aut:param name="period" value="0" />
		</aut:params>
		<aut:nodes>
			<aut:reference id="supernode" />
		</aut:nodes>
		<aut:events>
			<aut:reference id="connection" />
		</aut:events>
	</aut:process>
	
	<aut:process id="poisson1" handler="it.unipr.ce.dsg.deus.impl.process.RectangularPulsePoissonProcess">
		<aut:params>
			<aut:param name="meanArrival" value="1000" />
			<aut:param name="startVtThreshold" value="2000" />
			<aut:param name="stopVtThreshold" value="15000" />
		</aut:params>
		<aut:nodes>
			<aut:reference id="supernode" />
		</aut:nodes>
		<aut:events>
			<aut:reference id="randomwalk" />
		</aut:events>
	</aut:process>
	
	<aut:process id="periodic3" handler="it.unipr.ce.dsg.deus.impl.process.PeriodicProcess">
		<aut:params>
			<aut:param name="period" value="2500" />
		</aut:params>
		<aut:events>
		    <!-- aut:reference id="logPopulationSize" / -->
			<aut:reference id="logNodeDegree" />
		</aut:events>
	</aut:process>

	<!-- *** SIMULATION *** -->

	<aut:engine maxvt="4000" seed="123456789">
		<aut:logger level="ALL"/>
		<aut:processes>
			<aut:reference id="periodic1" />
			<aut:reference id="poisson1" />
			<aut:reference id="periodic3" />
		</aut:processes>
	</aut:engine>

</aut:automator>

=== dsg-unipr/deus/examples/basic/GrowthConnectionsExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<aut:automator
	xmlns:aut="http://dsg.ce.unipr.it/software/deus/schema/automator"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://dsg.ce.unipr.it/software/deus/schema/automator automator.xsd ">


	<!-- *** EVENTS *** -->

	<aut:event id="birth" handler="it.unipr.ce.dsg.deus.impl.event.BirthEvent"
	 schedulerListener="it.unipr.ce.dsg.deus.example.basic.BirthSchedulerListener"><!-- when scheduled, creates a new node -->
		<aut:params>
			<aut:param name="hasSameAssociatedNode" value="false" />
		</aut:params>
		<aut:events><!-- events to be scheduled on created node -->
		    <aut:reference id="connection" />
		</aut:events>
	</aut:event>

	<aut:event id="connection" handler="it.unipr.ce.dsg.deus.p2p.event.SingleConnectionEvent" schedulerListener="it.unipr.ce.dsg.deus.example.basic.SingleConnectionSchedulerListener" oneShot="true" >
		<aut:params>
			<aut:param name="isBidirectional" value="true" />
			<aut:param name="hasSameAssociatedNode" value="false" />
		</aut:params>
		<aut:events>
			<aut:reference id="disconnection" />
		</aut:events>
	</aut:event>

	<aut:event id="disconnection" handler="it.unipr.ce.dsg.deus.p2p.event.DisconnectionEvent" schedulerListener="it.unipr.ce.dsg.deus.example.basic.DisconnectionSchedulerListener" oneShot="true">
		<aut:params>
			<aut:param name="hasSameAssociatedNode" value="false" />
		</aut:params>
		<aut:events>
			<aut:reference id="death" />
		</aut:events>
	</aut:event>

	<aut:event id="death" handler="it.unipr.ce.dsg.deus.impl.event.DeathEvent" oneShot="true">
		<aut:params>
			<aut:param name="hasSameAssociatedNode" value="false" />
		</aut:params>
	</aut:event>	

	<aut:event id="logPopulationSize" handler="it.unipr.ce.dsg.deus.impl.event.LogPopulationSizeEvent" />

	<aut:event id="logNodeDegree" handler="it.unipr.ce.dsg.deus.p2p.event.LogNodeDegreeEvent" />


	<!-- *** NODE SPECIES *** -->

	<aut:node id="supernode" handler="it.unipr.ce.dsg.deus.p2p.node.Peer" />

	<!-- *** PROCESSES *** -->

	<!-- with 1/lambda = 50 and 1/lambda' = 20000, we have E[N] = 400 -->

	<aut:process id="periodic1" handler="it.unipr.ce.dsg.deus.impl.process.PeriodicProcess">
		<aut:params>
			<aut:param name="period" value="50" />
		</aut:params>
		<aut:nodes>
			<aut:reference id="supernode" />
		</aut:nodes>
		<aut:events>
			<aut:reference id="birth" />
		</aut:events>
	</aut:process>
	
	<aut:process id="periodic2" handler="it.unipr.ce.dsg.deus.impl.process.PeriodicProcess">
		<aut:params>
			<aut:param name="period" value="0" />
		</aut:params>
		<aut:nodes>
			<aut:reference id="supernode" />
		</aut:nodes>
		<aut:events>
			<aut:reference id="connection" />
		</aut:events>
	</aut:process>
	
	<aut:process id="poisson3" handler="it.unipr.ce.dsg.deus.impl.process.PoissonProcess">
		<aut:params>
			<aut:param name="meanArrival" value="5" />
		</aut:params>
		<aut:nodes>
			<aut:reference id="supernode" />
		</aut:nodes>
		<aut:events>
			<aut:reference id="death" />
		</aut:events>
	</aut:process>

	<aut:process id="poisson4" handler="it.unipr.ce.dsg.deus.impl.process.PoissonProcess">
		<aut:params>
			<aut:param name="meanArrival" value="20000" />
		</aut:params>
		<aut:nodes>
			<aut:reference id="supernode" />
		</aut:nodes>
		<aut:events>
			<aut:reference id="disconnection" />
		</aut:events>
	</aut:process>
	
	<aut:process id="periodic3" handler="it.unipr.ce.dsg.deus.impl.process.PeriodicProcess">
		<aut:params>
			<aut:param name="period" value="10000" />
		</aut:params>
		<aut:events>
		    <aut:reference id="logPopulationSize" />
			<!-- aut:reference id="logNodeDegree" / -->
		</aut:events>
	</aut:process>

	<!-- *** SIMULATION *** -->

	<aut:engine maxvt="100000" seed="123456789">
		<aut:logger level="ALL"/>
		<aut:processes>
			<aut:reference id="periodic1" />
			<aut:reference id="periodic3" />
		</aut:processes>
	</aut:engine>

</aut:automator>
